name: Publish Homebrew Formula

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    
    steps:
      - name: Get latest release tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "tag_name=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Get version from tag
        id: get_version
        env:
          RELEASE_TAG: ${{ steps.get_latest_tag.outputs.tag_name }}
        run: echo "version=${RELEASE_TAG#v}" >> $GITHUB_OUTPUT

      - name: Trigger Homebrew tap update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          repository: neptaco/homebrew-tap
          event-type: update-formula
          client-payload: '{"formula": "mcproc", "version": "${{ steps.get_version.outputs.version }}"}' 