name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test (without v prefix)'
        required: true
        default: '0.1.0'

permissions:
  contents: write

jobs:
  setup:
    name: Setup version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build release binaries
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: mcproc
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: mcproc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: mcproc
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: mcproc

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install protobuf compiler
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install protobuf
          else
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
          fi

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Set up file names
        id: file_names
        run: |
          BASE_NAME="${{ matrix.binary_name }}-${{ needs.setup.outputs.version }}-${{ matrix.target }}"
          echo "archive_name=${BASE_NAME}.tar.gz" >> $GITHUB_OUTPUT
          echo "sha_name=${BASE_NAME}.tar.gz.sha256" >> $GITHUB_OUTPUT

      - name: Package
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ steps.file_names.outputs.archive_name }} ${{ matrix.binary_name }}
          cd ../../..
          shasum -a 256 ${{ steps.file_names.outputs.archive_name }} > ${{ steps.file_names.outputs.sha_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}-${{ matrix.target }}
          path: |
            ${{ steps.file_names.outputs.archive_name }}
            ${{ steps.file_names.outputs.sha_name }}

  release:
    name: Create Release
    needs: [build, setup]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          tag_name: "v${{ needs.setup.outputs.version }}"
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          generate_release_notes: true

  update-homebrew:
    name: Update Homebrew Formula
    needs: [release, setup]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Homebrew tap update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          repository: neptaco/homebrew-tap
          event-type: update-formula
          client-payload: '{"formula": "mcproc", "version": "${{ needs.setup.outputs.version }}"}'